# Generated by Django 4.2.7 on 2023-11-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
