# Generated by Django 4.2.7 on 2023-11-05 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0003_familymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='group_names',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='username',
        ),
        migrations.AddField(
            model_name='familymember',
            name='group',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
