# Generated by Django 4.2.7 on 2023-11-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0006_customuser_donggop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='donggop',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
