# Generated by Django 4.2.7 on 2023-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0007_alter_customuser_donggop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
