# Generated by Django 4.2.7 on 2023-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0008_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sukien',
            field=models.BooleanField(default=False),
        ),
    ]
