# Generated by Django 4.2.7 on 2023-12-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0009_customuser_sukien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sukien',
            field=models.CharField(default='', max_length=255),
        ),
    ]
